services:
  mysql:
    image: mysql
    container_name: mysqlcont
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goodstudy
    networks:
      - mysqlnetwork

  goodstudyspring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goodstudycont
    ports:
      - "8090:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: goodstudy
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - mysqlnetwork

networks:
  mysqlnetwork: